### ISSUE TITLE
ParserError: Source file requires different compiler version (current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)

### ISSUE THREAD

**Issue by AldrinAJ** [ThisIsCodeXpert/CodeXpert-Tron-DApp-Template#2]
$ tronbox compile --compile-all

Error parsing /home/Documents/trontest/kookiekrak-TronLink-Demo-Messages-master/contracts/Migrations.sol: ParsedContract.sol:3:1: 
ParserError: Source file requires different compiler version (current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)
Compilation failed. See above.

Hi @ThisIsCodeXpert , Could you please advice me over this?
Thanks..

**Comment by shlokm289** [comment]
Since solidity has breaking changes in v 0.5.0 &  above, do the necessary changes in the smart contract and change the solidity versioning line to pragma solidity >=0.5.4 <0.6.0. Then the compilation and migration of the contracts works fine.

**Comment by shl0k28** [comment]
> $ tronbox compile --compile-all
> 
> Error parsing /home/Documents/trontest/kookiekrak-TronLink-Demo-Messages-master/contracts/Migrations.sol: ParsedContract.sol:3:1:
> ParserError: Source file requires different compiler version (current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)
> Compilation failed. See above.
> 
> Hi @ThisIsCodeXpert , Could you please advice me over this?
> Thanks..

Since solidity has breaking changes in v 0.5.0 & above, do the necessary changes in the smart contract and change the solidity versioning line to pragma solidity >=0.5.4 <0.6.0. Then the compilation and migration of the contracts works fine.

**Comment by ThisIsCodeXpert** [comment]
Hi,

Please check once again. we have updated it! Thanks for advice! :-)

Let us know if you find any other problem

**Comment by AldrinAJ** [comment]
@ThisIsCodeXpert Hi, thanks for you response..
I appreciate your efforts..
the issue had been solved previously, by choosing the correct compiler version. 
Thanks.. @shlokm289

**Comment by CAPTAINNEMO29** [comment]
ParserError: Source file requires different compiler version (current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)

im having the same problem, 

this would fix it? pragma solidity >=0.5.4 <0.6.0; in Migrations.sol?

**Comment by pironmind** [comment]
> > $ tronbox compile --compile-all
> > Error parsing /home/Documents/trontest/kookiekrak-TronLink-Demo-Messages-master/contracts/Migrations.sol: ParsedContract.sol:3:1:
> > ParserError: Source file requires different compiler version (current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)
> > Compilation failed. See above.
> > Hi @ThisIsCodeXpert , Could you please advice me over this?
> > Thanks..
> 
> Since solidity has breaking changes in v 0.5.0 & above, do the necessary changes in the smart contract and change the solidity versioning line to pragma solidity >=0.5.4 <0.6.0. Then the compilation and migration of the contracts works fine.

nice solution)))
